# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr.xdc

# Block Designs: bd/test/test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test || ORIG_REF_NAME==test} -quiet] -quiet

# IP: bd/test/ip/test_mpsoc_0/test_mpsoc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_mpsoc_0 || ORIG_REF_NAME==test_mpsoc_0} -quiet] -quiet

# IP: bd/test/ip/test_axi_gpio_0_0/test_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_axi_gpio_0_0 || ORIG_REF_NAME==test_axi_gpio_0_0} -quiet] -quiet

# IP: bd/test/ip/test_mpsoc_axi_periph_1/test_mpsoc_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_mpsoc_axi_periph_1 || ORIG_REF_NAME==test_mpsoc_axi_periph_1} -quiet] -quiet

# IP: bd/test/ip/test_rst_mpsoc_99M_0/test_rst_mpsoc_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_rst_mpsoc_99M_0 || ORIG_REF_NAME==test_rst_mpsoc_99M_0} -quiet] -quiet

# IP: bd/test/ip/test_auto_pc_0/test_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_auto_pc_0 || ORIG_REF_NAME==test_auto_pc_0} -quiet] -quiet

# XDC: /home/ubuntu/casper/project/test_vivado/myproj/zrf16_test.gen/sources_1/bd/test/test_ooc.xdc
